# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-14 17:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('db_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('comment_id', models.AutoField(primary_key=True, serialize=False)),
                ('comment_text', models.TextField()),
                ('comment_photo', models.ImageField(blank=True, null=True, upload_to='')),
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Comments',
            },
        ),
        migrations.AlterModelOptions(
            name='actors',
            options={'verbose_name': 'Actor', 'verbose_name_plural': 'Actors'},
        ),
        migrations.AlterModelOptions(
            name='cameramen',
            options={'verbose_name': 'Cameraman', 'verbose_name_plural': 'Cameramen'},
        ),
        migrations.AlterModelOptions(
            name='countries',
            options={'verbose_name': 'Country', 'verbose_name_plural': 'Countries'},
        ),
        migrations.AlterModelOptions(
            name='film_writers',
            options={'verbose_name': 'Film_writer', 'verbose_name_plural': 'Film_writers'},
        ),
        migrations.AlterModelOptions(
            name='filmmakers',
            options={'verbose_name': 'Filmmaker', 'verbose_name_plural': 'Filmmakers'},
        ),
        migrations.AlterModelOptions(
            name='films',
            options={'verbose_name': 'Film', 'verbose_name_plural': 'Films'},
        ),
        migrations.AlterModelOptions(
            name='producers',
            options={'verbose_name': 'Producer', 'verbose_name_plural': 'Producers'},
        ),
        migrations.AddField(
            model_name='comments',
            name='comment_film',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db_app.Films'),
        ),
        migrations.AddField(
            model_name='comments',
            name='comment_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
