# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-15 04:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_app', '0004_auto_20180115_0658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='comment_photo',
            field=models.ImageField(blank=True, default='def.jpg', null=True, upload_to='downloaded'),
        ),
    ]
